name: notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.0
  


dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
     

flutter:
  uses-material-design: true
  assets:
    - images/spl.png
    - images/bg.png
    - images/background_tile.jpg
    - images/icon.png
  

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true
  
